CREATE TABLE IF NOT EXISTS `form_workcomp_followup` (
    /* both extended and encounter forms need a last modified date */
    date datetime default NULL comment 'last modified date',
    /* these fields are common to all encounter forms. */
    id bigint(20) NOT NULL auto_increment,
    pid bigint(20) NOT NULL default 0,
    user varchar(255) default NULL,
    groupname varchar(255) default NULL,
    authorized tinyint(4) default NULL,
    activity tinyint(4) default NULL,
    date_accident datetime default NULL,
    description TEXT,
    WCBCase varchar(30),
    claim_number varchar(30),
    WCBRating varchar(30),
    insurance_W_code varchar(30),
    visit_tests TEXT,
    exam_changes TEXT,
    additioanl_body_parts TEXT,
    plan_changes TEXT,
    need_test_refs varchar(5),
    test_options varchar(255),
    ref_options varchar(255),
    next_appointment varchar(12),
    visit_treatments TEXT,
    condition_caused varchar(5),
    condition_complaints varchar(5),
    condition_history varchar(5),
    percent_impaired varchar(5),
    findings_text TEXT,
    work_status varchar(5),
    work_restrictions varchar(5),
    work_restrictions_text TEXT,
    restrictions_period varchar(12),
    work_options varchar(12),
    work_option_text TEXT,
    limit_options varchar(255),
    limits_quant_text TEXT,
    limits_period varchar(12),
    return_work_discuss varchar(12),
    benefit_rehab varchar(5),
    PRIMARY KEY (id)
) ENGINE=InnoDB;

